# Generated by Django 3.2.9 on 2021-12-06 15:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='project_title-country'),
            preserve_default=False,
        ),
    ]
