# Generated by Django 3.2.9 on 2021-12-06 15:55

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0007_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='network',
            field=models.ManyToManyField(to='virtualization.Network', verbose_name='Redes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='project_title_country'),
        ),
    ]
