# Generated by Django 3.2.9 on 2021-12-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0008_auto_20211206_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm',
            name='network',
        ),
    ]
