# Generated by Django 3.2.9 on 2021-12-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0009_remove_vm_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualization.network')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualization.vm')),
            ],
        ),
    ]
