# Generated by Django 3.2.9 on 2021-12-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0011_port_ip_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm',
            name='site',
        ),
    ]
